name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt (toutes branches)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Récupère tout l'historique

      - name: Vérifier la présence du script avant récupération
        run: ls -lah || echo "Fichiers non trouvés"

      - name: Récupérer `update_articles.py` depuis main
        run: |
          git checkout origin/main -- update_articles.py
          ls -lah update_articles.py || echo "Fichier introuvable après récupération"

      - name: Installer Python et pdfplumber
        run: |
          python -m pip install --upgrade pip
          pip install pdfplumber

      - name: Exécuter le script de mise à jour
        run: python update_articles.py

      - name: Installer Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Construire le site
        run: hugo --minify

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
