name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Change si ta branche principale est "master"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          submodules: true  # Nécessaire si le thème est un submodule
          fetch-depth: 0     # Important pour les sites avec GitInfo activé

      - name: Installer Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true  # Installe la version Extended

      - name: Construire le site
        run: hugo --minify

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
